{
 "title": "RRC Pod Details",
 "tags": [
  "spring boot",
  "rrc",
  "java"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "site", "label": "Site", "query": { "query": "label_values(up, rrc_site)" } },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "label_values(up{rrc_site=\"$site\"}, rrc_component)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(up{rrc_site=\"$site\", rrc_component=\"$type\"}, instance)"
    }
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": {
     "query": "label_values(hikaricp_connections{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}, pool)"
    }
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", area=\"heap\"}, id)"
    }
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", area=\"nonheap\"}, id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "x": 0, "y": 0, "w": 24, "h": 1 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "process_files_open_files{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}",
     "legendFormat": "Open Files"
    },
    {
     "expr": "process_files_max_files{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}",
     "legendFormat": "Max Files"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}*1000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  { "title": "HTTP Details", "type": "row", "gridPos": { "x": 0, "y": 14, "w": 24, "h": 1 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 15, "w": 4, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", uri!=\"/actuator/prometheus\"})"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "x": 4, "y": 15, "w": 20, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", status=~\"2.*\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "x": 0, "y": 22, "w": 4, "h": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", outcome=\"SERVER_ERROR\"})"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "x": 4, "y": 22, "w": 20, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", status=~\"5.*\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 29, "w": 12, "h": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri)(rate(http_server_requests_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "x": 12, "y": 29, "w": 12, "h": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri)(http_server_requests_seconds_sum{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}) / sum by(uri)(http_server_requests_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Status Code Rate (stacked)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 41, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status_class) (  label_replace(    rate(http_server_requests_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", uri!=\"/actuator/prometheus\"}[5m]),    \"status_class\", \"${1}xx\", \"status\", \"(.)..\"  ))",
     "legendFormat": "{{status_class}}"
    }
   ]
  },
  {
   "title": "Outcome Rate (stacked)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 41, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (outcome) (rate(http_server_requests_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Top 10 URIs by Request Rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 49, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (uri) (rate(http_server_requests_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", uri!=\"/actuator/prometheus\"}[5m])))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Top 10 URIs by Avg Latency",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 49, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10,   sum by (uri) (rate(http_server_requests_seconds_sum{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", uri!=\"/actuator/prometheus\"}[5m]))  /   sum by (uri) (rate(http_server_requests_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", uri!=\"/actuator/prometheus\"}[5m])))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  { "title": "JVM Statistics - Heaps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "repeat": "memory_pool_heap",
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "repeat": "memory_pool_nonheap",
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "JVM Statistics Threads/Buffers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_live_threads{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_peak_threads{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}[5m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}[5m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}",
     "legendFormat": "Classes Loaded"
    }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "irate(jvm_classes_unloaded_classes_total{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}[5m])",
     "legendFormat": "Classes Unloaded"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", id=\"direct\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", id=\"direct\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", id=\"mapped\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", id=\"mapped\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  { "title": "JVM Statistics - GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "GC Stop the World Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  { "title": "HikariCP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Connections Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "hikaricp_connections{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 106 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", pool=\"$hikaricp\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", pool=\"$hikaricp\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", pool=\"$hikaricp\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Connection Timeout Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connection Creation Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "hikaricp_connections_creation_seconds_sum{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", pool=\"$hikaricp\"} / hikaricp_connections_creation_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", pool=\"$hikaricp\"}",
     "legendFormat": "Creation Time"
    }
   ]
  },
  {
   "title": "Connection Usage Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 114 },
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", pool=\"$hikaricp\"} / hikaricp_connections_usage_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", pool=\"$hikaricp\"}",
     "legendFormat": "Usage Time"
    }
   ]
  },
  {
   "title": "Connection Acquire Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 114 },
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_sum{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", pool=\"$hikaricp\"} / hikaricp_connections_acquire_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", pool=\"$hikaricp\"}",
     "legendFormat": "Acquire Time"
    }
   ]
  },
  { "title": "Jetty Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "Thread Config Min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 121 },
   "targets": [
    {
     "expr": "jetty_threads_config_min{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}",
     "legendFormat": "Min threads"
    }
   ]
  },
  {
   "title": "HTTP Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 121 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", status=~\"5..\"}[1m]))",
     "legendFormat": "5xx - Server Errors"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", status=~\"4..\"}[1m]))",
     "legendFormat": "4xx - Client Errors"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", status=~\"2..\"}[1m]))",
     "legendFormat": "2xx - Success"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", status=~\"3..\"}[1m]))",
     "legendFormat": "3xx - Redirections"
    }
   ]
  },
  {
   "title": "Thread Config Max",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "jetty_threads_config_max{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}",
     "legendFormat": "Max threads"
    }
   ]
  },
  {
   "title": "Requests/second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 129 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}[1m]))",
     "legendFormat": "Requests per second"
    }
   ]
  },
  {
   "title": "Requests duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 129 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", status!~\"5..\"}[1m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(http_server_requests_seconds_max{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", status!~\"5..\"})",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "TOP 10",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 136 },
   "targets": [
    {
     "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}[1m])))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 136 },
   "targets": [
    {
     "expr": "jetty_threads_current{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}",
     "legendFormat": "Current thread"
    },
    {
     "expr": "jetty_threads_busy{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}",
     "legendFormat": "Busy thread"
    },
    {
     "expr": "jetty_threads_idle{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}",
     "legendFormat": "Idle threads"
    },
    {
     "expr": "jetty_threads_jobs{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\"}",
     "legendFormat": "Jobs  threads"
    }
   ]
  },
  { "title": "Logback Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 } },
  {
   "title": "INFO logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 146 },
   "targets": [
    {
     "expr": "irate(logback_events_total{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", level=\"info\"}[5m])",
     "legendFormat": "info",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "ERROR logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 146 },
   "targets": [
    {
     "expr": "irate(logback_events_total{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", level=\"error\"}[5m])",
     "legendFormat": "error",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "WARN logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 153 },
   "targets": [
    {
     "expr": "irate(logback_events_total{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", level=\"warn\"}[5m])",
     "legendFormat": "warn",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "DEBUG logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 153 },
   "targets": [
    {
     "expr": "irate(logback_events_total{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", level=\"debug\"}[5m])",
     "legendFormat": "debug",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "TRACE logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 153 },
   "targets": [
    {
     "expr": "irate(logback_events_total{rrc_site=\"$site\", rrc_component=\"$type\", instance=\"$pod\", level=\"trace\"}[5m])",
     "legendFormat": "trace",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}